---
apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  displayName: secure-default
  name: secure-default
  organization: tetrate
  tenant: digital-nonprod
  workspace: svcauth-httpbin
spec:
  defaultSecuritySetting:
    authenticationSettings:
      trafficMode: REQUIRED
    authorization:
      mode: CUSTOM
      serviceAccounts:
        - svcauth-sleep/sleep-auth
  displayName: secure-default