apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep-auth
---
apiVersion: v1
kind: Service
metadata:
  name: sleep-auth
  labels:
    app: sleep-auth
    service: sleep-auth
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: sleep-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-auth
  template:
    metadata:
      labels:
        app: sleep-auth
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: sleep-auth
      containers:
      - name: sleep
        image: curlimages/curl
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
